services:
  database:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-lti}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - application

  application:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: lti:latest
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      - "443:443/udp" # HTTP/3
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - storage_data:/app/storage
    networks:
      - application

volumes:
  db_data:

networks:
  application:
    driver: bridge
